apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-deployment
        image: app1:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
