# -*- mode: ruby -*-
# vi: set ft=ruby :

MASTER = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.vm.define "oabdelhaS", primary: true do |server|
      server.vm.network "private_network", ip: MASTER
      server.vm.synced_folder "./shared", "/tmp/shared"
      server.vm.hostname = "oabdelhaS"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "2"
      end
      server.vm.provision "file", source: "confs", destination: "/tmp/confs"
      server.vm.provision "shell", path: "scripts/server.sh", env: {"MASTER" => MASTER}
  end
end