# -*- mode: ruby -*-
# vi: set ft=ruby :

MASTER = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "oabdelhaS", primary: true do |master|
      master.vm.network "private_network", ip: MASTER
      master.vm.hostname = "oabdelhaS"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "2"
      end
      master.vm.provision "file", source: "confs", destination: "/tmp/confs"
      master.vm.provision "shell", path: "scripts/master.sh", env: {"MASTER" => MASTER}
  end
end