# -*- mode: ruby -*-
# vi: set ft=ruby :

MASTER = "192.168.56.110"
SLAVE = "192.168.56.111"


Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos7"

    config.vm.define "server", primary: true do |server|
        server.vm.network "private_network", ip: MASTER
        server.vm.synced_folder "./shared", "/tmp/shared"
        server.vm.hostname = "ahkechaS"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "2"
        end
        server.vm.provision "shell", path: "scripts/server.sh", env: {"MASTER" => MASTER, "SLAVE" => SLAVE}
    end

    config.vm.define "slave" do |slave|
        slave.vm.network "private_network", ip: SLAVE
        slave.vm.synced_folder "./shared", "/tmp/shared"
        slave.vm.hostname = "ahkechaSW"
        slave.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
        end
        slave.vm.provision "shell", path: "scripts/sworker.sh", env: {"MASTER" => MASTER}
    end
end
